<a href="https://colab.research.google.com/github/Faspeice/ml/blob/lr1/lr1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 1  
## Работа с библиотекой pandas

**Цель работы:** познакомиться с использованием библиотеки pandas при решении практических задач, связанных с анализом данных.

Проанализируем датасет `student-mat`. Датасет содержит сведения о студентах двух школ. Смысл задачи — определять, основываясь на этих данных, итоговую оценку студента. Набор данных включает следующие атрибуты:


- **school** – школа ('GP' – Gabriel Pereira или 'MS' – Mousinho da Silveira).  
- **sex** – пол студента ('F' – female или 'M' – male).  
- **age** – возраст студента.  
- **address** – домашний адрес студента ('U' – городской или 'R' – сельский).  
- **famsize** – размер семьи ('LE3' – меньше или равно 3 или 'GT3' – больше чем 3).  
- **Pstatus** – статус совместного проживания родителей ('T' – совместное проживание или 'A' – раздельное проживание).  
- **Medu** – образование матери (0 – нет, 1 – начальное (4 класс), 2 – 9 классы, 3 – среднее или 4 – высшее).  
- **Fedu** – образование отца (0 – нет, 1 – начальное (4 класс), 2 – 9 классы, 3 – среднее или 4 – высшее).  
- **Mjob** – работа матери (учитель, медицинское обслуживание, связанные с гражданскими услугами (административными или полицейскими), на дому или другое).  
- **Fjob** – работа отца (учитель, медицинское обслуживание, связанные с гражданскими услугами (административными или полицейскими), на дому или другое).  
- **famrel** – качество семейных отношений (от 1 – очень плохо до 5 – отлично).  
- **freetime** – свободное время после школы (от 1 – очень мало до 5 – очень много).  
- **goout** – встречи с друзьями (от 1 – очень мало до 5 – очень много).  
- **Dalc** – потребление алкоголя в рабочий день (Daily Alcohol Consumption) (от 1 – очень низкое до 5 – очень высокое).  
- **Walc** – еженедельное потребление алкоголя (Weekly Alcohol Consumption) (от 1 – очень низкое до 5 – очень высокое).  
- **health** – текущее состояние здоровья (от 1 – очень плохое до 5 – очень хорошее).  
- **absences** – количество пропусков занятий в школе (от 0 до 93).  
- **G1** – оценка за первый период (от 0 до 20).  
- **G2** – оценка за второй период (от 0 до 20).  
- **G3** – итоговая оценка (от 0 до 20, целевой результат).

## 1. Импортируйте необходимые библиотеки

In [4]:
import numpy as np
import pandas as pd

##2. Импортируйте набор данных из файла student-mat.csv и поместите его в объект DataFramne

In [5]:
url = "https://raw.githubusercontent.com/faspeice/ml/lr1/student-mat.csv"
df = pd.read_csv(url)

## 3. Выведите 10 первых строк

In [6]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

## 4. Сколько строк и столбцов в наборе данных?

In [7]:
print("Количество строк:", df.shape[0])
print("Количество столбцов:", df.shape[1])

Количество строк: 395
Количество столбцов: 33

## 5. Получите сводную информацию по датафрейм

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

## 6. Что является индексом этого набора данных?

In [9]:
df.index

RangeIndex(start=0, stop=395, step=1)

## 7. Создайте новый датафрейм fam, выполнив срез от столбца school до
##столбца famrel и удалив все столбцы от traveltime до romantic включи-
##тельно (оставив только характеристики семьи)

In [10]:
fam = df.loc[:, "school":"famrel"].drop(df.loc[:, "traveltime":"romantic"].columns, axis=1)
fam.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,famrel
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,5
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,4
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,3
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,4

## 8. Определите процент городских и сельских студентов в каждой школе

In [11]:
df.groupby("school")["address"].value_counts(normalize=True) * 100

school  address
GP      U          81.948424
        R          18.051576
MS      R          54.347826
        U          45.652174
Name: proportion, dtype: float64

## 9. У какого процента студентов (по школам) и мать и отец имеют высшее
##образование?

In [12]:
high_ed = df[(df["Medu"] == 4) & (df["Fedu"] == 4)]
(high_ed.groupby("school").size() / df.groupby("school").size()) * 100

school
GP    17.765043
MS    17.391304
dtype: float64

## 10. У какого процента студентов (по школам) и мать и отец вообще не
##имеют образования?

In [13]:
no_ed = df[(df["Medu"] == 0) & (df["Fedu"] == 0)]
no_ed.groupby("school").size().div(df.groupby("school").size(), fill_value=0) * 100

school
GP    0.0
MS    0.0
dtype: float64

В данном датасете нет студентов, у которых мать и отец вообще не имеют образования.

## 11. Какой процент родителей, имеющих высшее образование, проживает
##совместно?

In [14]:
parents_high = df[(df["Medu"] == 4) | (df["Fedu"] == 4)]
print("Процент таких семей",float((parents_high["Pstatus"].value_counts(normalize=True) * 100)["T"]))

Процент таких семей 86.62420382165605

## 12. Определите процент семей, в которых один из родителей имеет высшее
##образование, а другой не имеет, но проживают совместно

In [15]:
mixed = df[((df["Medu"] == 4) & (df["Fedu"] != 4)) | ((df["Medu"] != 4) & (df["Fedu"] == 4))]
mixed_together = mixed[mixed["Pstatus"] == "T"]
print("Процент таких семей: ",len(mixed_together) / len(df) * 100)

Процент таких семей:  18.9873417721519

## 13. Какое качество семейных отношений в этих семьях?

In [16]:
mixed_together["famrel"].describe()

count    75.000000
mean      3.933333
std       0.875080
min       1.000000
25%       4.000000
50%       4.000000
75%       4.500000
max       5.000000
Name: famrel, dtype: float64

В среднем качество семейных отношений в таких семьях в районе 4.

## 14. У скольких студентов работа одного или обоих родителей связана с
##гражданскими услугами (административными или полицейскими)?

In [17]:
civil = df[(df["Mjob"] == "services") | (df["Fjob"] == "services")]
print("Количество таких студентов: ",len(civil))

Количество таких студентов:  171

## 15. Преобразуйте значения числового столбца age в числа с плавающей за-
##пятой и получите сводку статистик для этого столбца

In [18]:
df["age"] = df["age"].astype(float)
df["age"].describe()

count    395.000000
mean      16.696203
std        1.276043
min       15.000000
25%       16.000000
50%       17.000000
75%       18.000000
max       22.000000
Name: age, dtype: float64